const actionTypes = {
  TOGGLE_FILTER: "TOGGLE_FILTER",
  SET_SORT_CHEAPEST: "SET_SORT_CHEAPEST",
  SET_SORT_FASTEST: "SET_SORT_FASTEST",
  SET_SORT_OPTIMAL: "SET_SORT_OPTIMAL",
  SET_SEARCH_ID: "SET_SEARCH_ID",
  LOADING_START: "LOADING_START",
  LOADING_ERROR: "LOADING_ERROR",
  TICKETS_LOAD: "TICKETS_LOAD",
};

export default actionTypes;
